#!/bin/bash

TAG="opensync-bcm-template"
CCWRAP="${CCWRAP:-ucw}"
ENTRYPOINT="/bin/sh -c"

usage()
{
    cat << EOF
usage: [ENVOPT] $0 [OPTIONS] [COMMAND] [ARGS]
ENVOPT:
DOCK_OPT=... : additional docker options
OPTIONS:
  --root : run as root instead of user this also skips
           mounting of home, passwd,...
EOF
    exit 255
}

run_docker()
{
    # build docker image if it does not exist
    if [ $(docker images -q $TAG | wc -l) != 1 ]; then
        ( cd `dirname $0`; ./build-docker-image )
    fi

    ARGS=(
    --rm
    --env TERM
    --interactive
    --tmpfs=/tmp:exec
    -edebian_chroot=DOCKER:"$TAG"
    -h"$TAG"
    )

    [ -t 1 -a -t 0 ] && {
        ARGS+=("--tty")
    }

    [ "${ROOT:-no}" = "no" ] && {
        ARGS+=(
        -eHOME="$HOME"
        -v/home:/home
        -v/etc/passwd:/etc/passwd
        -v/etc/group:/etc/group
        -u$UID:$UID
        )
    }

    # Add Jenkins workspaces to docker
    [ -d "/data/jenkins/" ] && {
        ARGS+=("-v/data/jenkins:/data/jenkins")
    }

    ARGS+=(-w"$PWD")

    case "${CCWRAP}" in
        ucw)
            ARGS+=("--entrypoint" "/usr/local/bin/ucw")
            ;;
        hexec)
            ARGS+=("--entrypoint" "/usr/local/bin/hucw")
            ;;
    esac

    ARGS+=($DOCK_OPT)

    ARGS+=("$TAG")

    # Run bash by default
    [ "$#" -eq 0 ] && { ARGS+=("/bin/bash" "-i"); }

    echo docker run "${ARGS[@]}" "$@"
    echo
    docker run "${ARGS[@]}" "$@"

}

#
# Parse arguments
#
while true
do
    case "$1" in
        --)
            shift
            break
            ;;
        -h)
            usage
            ;;
        --ucw)
            CCWRAP="ucw"
            ;;
        --noucw)
            CCWRAP="none"
            ;;
        --hexec)
            CCWRAP="hexec"
            ;;
        --root)
            ROOT="yes"
            ;;
        -*)
            echo "Unknown argument: $1"
            exit 255
            ;;
        *)
            break
    esac
    shift
done

run_docker "$@"
