#!/bin/sh

if [ $# -ne 1 ];
then
    echo "Usage: `basename $0` <rootfs-path>"
    exit 1
fi

ROOTFS=$1

echo "###### post-install ${ROOTFS} #######"

mkdir -p ${ROOTFS}/overlay
mkdir -p ${ROOTFS}/rom
mkdir -p ${ROOTFS}/rootfs_data
mkdir -p ${ROOTFS}/root

##
# Version
#
cp -a "${ROOTFS}/${INSTALL_PREFIX}"/.version* "${ROOTFS}"

##
# System services
#
ln -sf ../init.d/mount_overlay ${ROOTFS}/etc/rc3.d/S260mount_overlay
ln -sf ../init.d/boot ${ROOTFS}/etc/rc3.d/S26boot
ln -sf ../init.d/boot ${ROOTFS}/etc/rc3.d/K26boot
ln -sf ../init.d/syslogd ${ROOTFS}/etc/rc3.d/S28syslogd
ln -sf ../init.d/htpdate ${ROOTFS}/etc/rc3.d/S49htpdate
ln -sf ../init.d/debugnet ${ROOTFS}/etc/rc3.d/S50debugnet
ln -sf ../init.d/dropbear ${ROOTFS}/etc/rc3.d/S51dropbear
ln -sf ../init.d/firewall ${ROOTFS}/etc/rc3.d/S60firewall

if [ "$CONFIG_WPD_ENABLED" = "y" ]; then
    ln -sf ../init.d/wpd ${ROOTFS}/etc/rc3.d/S29wpd
    # remove wdtd.sh from bcm5.4.2 if using opensync wpd
    rm ${ROOTFS}/etc/rc3.d/S26wdtd
fi

##
# BCM
#
ln -sf ../init.d/bcm_perf_boost ${ROOTFS}/etc/rc3.d/S48bcm_perf_boost

##
# OpenSync
#
ln -sf ../init.d/openvswitch ${ROOTFS}/etc/rc3.d/S90openvswitch
ln -sf ../init.d/opensync ${ROOTFS}/etc/rc3.d/S99opensync
ln -sf ../init.d/healthcheck ${ROOTFS}/etc/rc3.d/S99healthcheck
