#!/bin/sh

start()
{
    bootconfig --write boot_log
}

stop()
{
    return
}


case "$1" in
    start)
        start
        ;;

    stop|restart)
        stop
        ;;

    *)
        echo "$0: unrecognized option $1"
        exit 1
        ;;
esac
