#!/bin/sh

mount_overlay()
{
    mount -t ubifs ubi:rootfs_overlay /overlay > /dev/null 2>&1 || {
        echo "No overlay filesystem."
        return
    }

    echo "Mounting overlay filesystem"

    mkdir -p /overlay/upper
    mkdir -p /overlay/work
    mount -t overlay overlay -o lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work /overlay

    # Move mount points to the overlay
    cat /proc/mounts | cut -d ' ' -f 2 | sort | while read MNT
    do
        case "$MNT" in
            "/"|"/overlay")
                ;;
            "/proc")
                # /proc shall be moved last as "mount" requires it
                ;;
            *)
                mountpoint -q "$MNT" && {
                    mkdir -p "/overlay/$MNT"
                    mount --move "$MNT" "/overlay/$MNT"
                }
                ;;
        esac
    done

    # move /proc
    mkdir -p "/overlay/proc"
    mount --move "/proc" "/overlay/proc"

    # Switch to new root filesystem
    echo "Pivoting overlay root"
    pivot_root /overlay /overlay/rom
    echo "Done mounting overlay filesystem"
}


start()
{
    mount_overlay

    # Enable panic on OOM
    echo "Enabling PANIC on OOM"
    echo 1 > /proc/sys/vm/panic_on_oom

    mkdir -p /var/run
    mkdir -p /var/log
    mkdir -p /var/lock
    mkdir -p /var/state
    mkdir -p /tmp/.uci
    mkdir -p /tmp/.jail
    touch /var/log/wtmp
    touch /var/log/lastlog
    touch /tmp/resolv.conf
    ln -sf /tmp/resolv.conf /etc/resolv.conf
    [ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe
}

stop()
{
    echo 'Explicit umount of /data partition ... '
    umount /data
}

case "$1" in
    start)
        echo "Running boot script..."
        # these are some miscellaneous stuff without a good home
        start
        exit 0
        ;;

    stop)
        stop
        exit 0
        ;;

    *)
        echo "$0: unrecognized option $1"
        exit 1
        ;;
esac
