#!/bin/sh -e
# {# jinja-parse #}
INSTALL_PREFIX={{INSTALL_PREFIX}}

START=60

PID_FILE_PREFIX=/var/run/udhcpc.pid
INTERFACES="eth0"
VLAN=4

source "${INSTALL_PREFIX}/scripts/vlan.funcs.sh"

start()
{
    for IF in $INTERFACES
    do
        test -e /sys/class/net/$IF || continue
        VIF="$(vlan_ifname $IF $VLAN)"
        vlan_add $IF $VLAN

        ifconfig $IF up
        ifconfig $VIF up
        start-stop-daemon -K -x /sbin/udhcpc -p $PID_FILE_PREFIX.$VIF -t || \
        start-stop-daemon -S -x /sbin/udhcpc -p $PID_FILE_PREFIX.$VIF -b -m -- -s ${INSTALL_PREFIX}/scripts/udhcpc.debugnet.sh -f -S -i $VIF -C -o -O subnet
    done
}

stop()
{
    for IF in $INTERFACES
    do
        test -e /sys/class/net/$IF || continue
        VIF="$(vlan_ifname $IF $VLAN)"

        ! start-stop-daemon -K -x /sbin/udhcpc -p $PID_FILE_PREFIX.$VIF -t || \
        start-stop-daemon -K -x /sbin/udhcpc -p $PID_FILE_PREFIX.$VIF

        vlan_del $IF $VLAN
    done
}

case "$1" in
    boot) start ;;
    start) start ;;
    stop) stop ;;
    *) exit 1 ;;
esac
