#!/bin/sh
# {# jinja-parse #}
INSTALL_PREFIX={{INSTALL_PREFIX}}

START=60

start()
{
    ${INSTALL_PREFIX}/bin/iptables_cmd.sh boot
}


case "$1" in
    start)
        start
        exit 0
        ;;

    stop)
        echo "Stopping firewall not implemented ..."
        exit 1
        ;;

    *)
        echo "$0: unrecognized option $1"
        exit 1
        ;;
esac
