#!/bin/sh

export PATH="/opt/sbin:/opt/bin:/usr/sbin:/sbin:/usr/bin:/bin/:$PATH"

start()
{
    echo "Starting syslogd $(which syslogd) and klogd $(which klogd) ..."
    syslogd -s 1024 -O /var/log/messages -S -b 1
    klogd
}

stop()
{
    echo "Stopping syslogd ..."
    killall syslogd
    killall klogd
}


case "$1" in
    start)
        start
        exit 0
        ;;

    stop)
        stop
        exit 0
        ;;

    *)
        echo "$0: unrecognized option $1"
        exit 1
        ;;
esac
