#!/bin/sh

LOG_NAME="${0##*/}"

log()
{
    logger -s -t "$LOG_NAME" $@
}

bcm_performance_boost()
{
    # Apparently this is needed to get good WiFi performance on BCM
    pgrep 'dhd0_dpc|wfd0-thrd|wfd1-thrd|skb_free_task|bcmsw_rx|fc_task' | xargs -n 1 chrt -r -p 5 | log
}

case "$1" in
    start|restart)
        bcm_performance_boost
        ;;

    stop)
        ;;

    *)
        echo "$0: Invalid options: $@"
        exit 1
esac
