#!/bin/sh
# {# jinja-parse #}
#
# OpenSync reference board specifics
#

INSTALL_PREFIX={{INSTALL_PREFIX}}

START=60

start()
{
    ${INSTALL_PREFIX}/bin/fan.sh | logger -t FAN
}

case "$1" in
    start)
        start
        exit 0
        ;;

    stop)
        echo "Stopping fan not implemented ..."
        exit 1
        ;;

    *)
        echo "$0: unrecognized option $1"
        exit 1
        ;;
esac
